name: Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master , codecov ]
  push:
    branches: [ master , codecov ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - name: set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Run Tests
        run : ng test ngx-scrollbar --watch=false --no-progress --browsers=ChromeHeadless --code-coverage
        
      - name: Build Coverage Report
        run : ./node_modules/.bin/codecov

      - name: Upload to Codecov.io
        env:
          CODECOV_TOKEN: e0c1b68e-a6ba-445a-a32e-8e88fcec0d86
        shell: bash
        run: |
          bash <(curl -s https://codecov.io/bash)
